# Generated by Django 5.1.3 on 2024-11-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='default_actors.jpeg', upload_to='pictures'),
        ),
    ]
